version: "3.7"
services:

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - frontend

  webapp:
    build: .
    ports:
      - "80:80"
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USE_REDIS: "true"
    networks:
      - frontend
    depends_on:
      - redis

networks:
  frontend: